### ISSUE TITLE
cyvcf2 wheel build fail on 0.30.19~0.30.22 (python3.11 + arm64 + debain bookworm)

### ISSUE THREAD

**Issue by graphenn** [brentp/cyvcf2#274]
```
#26 92.48       gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ihtslib -Icyvcf2 -I/tmp/pip-build-env-cl11uelk/overlay/lib/python3.11/site-packages/numpy/core/include -I/usr/local/include/python3.11 -c cyvcf2/helpers.c -o build/temp.linux-aarch64-cpython-311/cyvcf2/helpers.o -Wno-sign-compare -Wno-unused-function -Wno-strict-prototypes -Wno-unused-result -Wno-discarded-qualifiers
#26 92.48       cyvcf2/helpers.c: In function ‘as_gts’:
#26 92.48       cyvcf2/helpers.c:7:21: warning: variable ‘found’ set but not used [-Wunused-but-set-variable]
#26 92.48           7 |     int missing= 0, found=0;
#26 92.48             |                     ^~~~~
#26 92.48       gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ihtslib -Icyvcf2 -I/tmp/pip-build-env-cl11uelk/overlay/lib/python3.11/site-packages/numpy/core/include -I/usr/local/include/python3.11 -c htslib/bcf_sr_sort.c -o build/temp.linux-aarch64-cpython-311/htslib/bcf_sr_sort.o -Wno-sign-compare -Wno-unused-function -Wno-strict-prototypes -Wno-unused-result -Wno-discarded-qualifiers
#26 92.48       gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ihtslib -Icyvcf2 -I/tmp/pip-build-env-cl11uelk/overlay/lib/python3.11/site-packages/numpy/core/include -I/usr/local/include/python3.11 -c htslib/bgzf.c -o build/temp.linux-aarch64-cpython-311/htslib/bgzf.o -Wno-sign-compare -Wno-unused-function -Wno-strict-prototypes -Wno-unused-result -Wno-discarded-qualifiers
#26 92.48       gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ihtslib -Icyvcf2 -I/tmp/pip-build-env-cl11uelk/overlay/lib/python3.11/site-packages/numpy/core/include -I/usr/local/include/python3.11 -c htslib/cram/cram_codecs.c -o build/temp.linux-aarch64-cpython-311/htslib/cram/cram_codecs.o -Wno-sign-compare -Wno-unused-function -Wno-strict-prototypes -Wno-unused-result -Wno-discarded-qualifiers
#26 92.48       htslib/cram/cram_codecs.c:54:10: fatal error: ../htscodecs/htscodecs/varint.h: No such file or directory
#26 92.48          54 | #include "../htscodecs/htscodecs/varint.h"
#26 92.48             |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#26 92.48       compilation terminated.
#26 92.48       error: command '/usr/bin/gcc' failed with exit code 1
```

0.30.18 can build successfully

the pip run in a docker container
```
uname -a
Linux mywork-0 5.10.0-60.18.0.50.r865_35.hce2.aarch64 #1 SMP Sun Mar 26 18:01:01 UTC 2023 aarch64 GNU/Linux
```

**Comment by brentp** [comment]
Hi, can you check if this is fixed with 0.30.22 and higher?

**Comment by graphenn** [comment]
Yes, I encountered the issue on version 0.30.22 and then checked previous versions. I found that it could still compile on 0.30.18, but it stopped working from 0.30.19 onwards.

**Comment by CholoTook** [comment]
There seem to be enough build issues to warrant a 'build test framework'.

I've tried to kick things off here:
https://github.com/brentp/cyvcf2/pull/283

**Comment by brentp** [comment]
@CholoTook please note the current CI setup with already tests this.

**Comment by CholoTook** [comment]
Oh, is that configured publicly? Or is it happening 'within' GitHub?

Having 'known good' setups to point at should help close these 'I cant install it' issues right?

What I liked about the docker approach I used is that it is easy to tweak all the versions to test specific combinations. I can't find the CI to see if that is also possible.

**Comment by CholoTook** [comment]
Here I guess:
https://github.com/brentp/cyvcf2/blob/main/.github/workflows/build.yml

How come it keeps failing?
